export function providerFailure(status?: number): string {
  if (status === 401 || status === 403)
    return "Provider authentication or access denied. Check the selected provider API key and project permissions in Settings.";
  if (status === 429)
    return "Provider quota or rate limit reached. Check billing/quota for your API project, or retry later.";
  if (status === 400 || status === 404)
    return "The selected model or requested tools are unavailable for this API project. Choose another supported model in Settings.";
  if (status && status >= 500)
    return "The provider is temporarily unavailable. Retry or choose a configured fallback model.";
  return "The provider connection failed or timed out. Check your network and provider settings, then retry.";
}
export class ProviderRequestError extends Error {
  constructor(public status?: number) {
    super(providerFailure(status));
  }
}

/** Only display messages generated by our connection layer, never raw server content. */
export function liveFailureMessage(message: unknown): string {
  const known = new Set([
    ...[undefined, 400, 401, 403, 404, 429, 500, 503].map(providerFailure),
    "Live voice could not continue. Check your provider key, model access and quota, then reconnect.",
    "This live session reached ten minutes. Start a new conversation.",
    "Add an API key and select an available live model in Settings.",
    "This live session reached its audio limit. Start a new conversation.",
    "Microphone chunk exceeded its limit.",
    "Microphone audio could not be sent. Reconnect to continue.",
    "Conversation input limit reached.",
  ]);
  return typeof message === "string" && known.has(message)
    ? message
    : "The live session failed. Check provider settings and retry; source verification is separate from generated speech.";
}
