// Name metadata only: the Muktika list, not approved source passages.
export const UPANISHAD_SCOPE = "muktika-upanishads";
export const UPANISHAD_TARGETS = [
  ["isha-upanishad", "Isha Upanishad"],
  ["kena-upanishad", "Kena Upanishad"],
  ["katha-upanishad", "Katha Upanishad"],
  ["prashna-upanishad", "Prashna Upanishad"],
  ["mundaka-upanishad", "Mundaka Upanishad"],
  ["mandukya-upanishad", "Mandukya Upanishad"],
  ["taittiriya-upanishad", "Taittiriya Upanishad"],
  ["aitareya-upanishad", "Aitareya Upanishad"],
  ["chandogya-upanishad", "Chandogya Upanishad"],
  ["brihadaranyaka-upanishad", "Brihadaranyaka Upanishad"],
  ["brahma-upanishad", "Brahma Upanishad"],
  ["kaivalya-upanishad", "Kaivalya Upanishad"],
  ["jabala-upanishad", "Jabala Upanishad"],
  ["shvetashvatara-upanishad", "Shvetashvatara Upanishad"],
  ["hamsa-upanishad", "Hamsa Upanishad"],
  ["aruneya-upanishad", "Aruneya Upanishad"],
  ["garbha-upanishad", "Garbha Upanishad"],
  ["narayana-upanishad", "Narayana Upanishad"],
  ["paramahamsa-upanishad", "Paramahamsa Upanishad"],
  ["amritabindu-upanishad", "Amritabindu Upanishad"],
  ["amritanada-upanishad", "Amritanada Upanishad"],
  ["atharvashiras-upanishad", "Atharvashiras Upanishad"],
  ["atharvashikha-upanishad", "Atharvashikha Upanishad"],
  ["maitrayaniya-upanishad", "Maitrayaniya Upanishad"],
  ["kaushitaki-upanishad", "Kaushitaki Upanishad"],
  ["brihajjabala-upanishad", "Brihajjabala Upanishad"],
  ["nrisimhatapaniya-upanishad", "Nrisimhatapaniya Upanishad"],
  ["kalagnirudra-upanishad", "Kalagnirudra Upanishad"],
  ["maitreya-upanishad", "Maitreya Upanishad"],
  ["subala-upanishad", "Subala Upanishad"],
  ["kshurika-upanishad", "Kshurika Upanishad"],
  ["mantrika-upanishad", "Mantrika Upanishad"],
  ["sarvasara-upanishad", "Sarvasara Upanishad"],
  ["niralamba-upanishad", "Niralamba Upanishad"],
  ["shukarahasya-upanishad", "Shukarahasya Upanishad"],
  ["vajrasuchi-upanishad", "Vajrasuchi Upanishad"],
  ["tejobindu-upanishad", "Tejobindu Upanishad"],
  ["nadabindu-upanishad", "Nadabindu Upanishad"],
  ["dhyanabindu-upanishad", "Dhyanabindu Upanishad"],
  ["brahmavidya-upanishad", "Brahmavidya Upanishad"],
  ["yogatattva-upanishad", "Yogatattva Upanishad"],
  ["atmabodha-upanishad", "Atmabodha Upanishad"],
  ["naradaparivrajaka-upanishad", "Naradaparivrajaka Upanishad"],
  ["trishikhibrahmana-upanishad", "Trishikhibrahmana Upanishad"],
  ["sita-upanishad", "Sita Upanishad"],
  ["yogachudamani-upanishad", "Yogachudamani Upanishad"],
  ["nirvana-upanishad", "Nirvana Upanishad"],
  ["mandalabrahmana-upanishad", "Mandalabrahmana Upanishad"],
  ["dakshinamurti-upanishad", "Dakshinamurti Upanishad"],
  ["sharabha-upanishad", "Sharabha Upanishad"],
  ["skanda-upanishad", "Skanda Upanishad"],
  ["mahanarayana-upanishad", "Mahanarayana Upanishad"],
  ["advayataraka-upanishad", "Advayataraka Upanishad"],
  ["ramarahasya-upanishad", "Ramarahasya Upanishad"],
  ["ramatapaniya-upanishad", "Ramatapaniya Upanishad"],
  ["vasudeva-upanishad", "Vasudeva Upanishad"],
  ["mudgala-upanishad", "Mudgala Upanishad"],
  ["shandilya-upanishad", "Shandilya Upanishad"],
  ["paingala-upanishad", "Paingala Upanishad"],
  ["bhikshuka-upanishad", "Bhikshuka Upanishad"],
  ["maha-upanishad", "Maha Upanishad"],
  ["shariraka-upanishad", "Shariraka Upanishad"],
  ["yogashikha-upanishad", "Yogashikha Upanishad"],
  ["turiyatitavadhuta-upanishad", "Turiyatitavadhuta Upanishad"],
  ["sannyasa-upanishad", "Sannyasa Upanishad"],
  ["paramahamsaparivrajaka-upanishad", "Paramahamsaparivrajaka Upanishad"],
  ["akshamalika-upanishad", "Akshamalika Upanishad"],
  ["avyakta-upanishad", "Avyakta Upanishad"],
  ["ekakshara-upanishad", "Ekakshara Upanishad"],
  ["annapurna-upanishad", "Annapurna Upanishad"],
  ["surya-upanishad", "Surya Upanishad"],
  ["akshi-upanishad", "Akshi Upanishad"],
  ["adhyatma-upanishad", "Adhyatma Upanishad"],
  ["kundika-upanishad", "Kundika Upanishad"],
  ["savitri-upanishad", "Savitri Upanishad"],
  ["atma-upanishad", "Atma Upanishad"],
  ["pashupatabrahma-upanishad", "Pashupatabrahma Upanishad"],
  ["parabrahma-upanishad", "Parabrahma Upanishad"],
  ["avadhuta-upanishad", "Avadhuta Upanishad"],
  ["tripuratapini-upanishad", "Tripuratapini Upanishad"],
  ["devi-upanishad", "Devi Upanishad"],
  ["tripura-upanishad", "Tripura Upanishad"],
  ["katharudra-upanishad", "Katharudra Upanishad"],
  ["bhavana-upanishad", "Bhavana Upanishad"],
  ["rudrahridaya-upanishad", "Rudrahridaya Upanishad"],
  ["yogakundalini-upanishad", "Yogakundalini Upanishad"],
  ["bhasmajabala-upanishad", "Bhasmajabala Upanishad"],
  ["rudrakshajabala-upanishad", "Rudrakshajabala Upanishad"],
  ["ganapati-upanishad", "Ganapati Upanishad"],
  ["darshana-upanishad", "Darshana Upanishad"],
  ["tarasara-upanishad", "Tarasara Upanishad"],
  ["mahavakya-upanishad", "Mahavakya Upanishad"],
  ["panchabrahma-upanishad", "Panchabrahma Upanishad"],
  ["pranagnihotra-upanishad", "Pranagnihotra Upanishad"],
  ["gopalatapaniya-upanishad", "Gopalatapaniya Upanishad"],
  ["krishna-upanishad", "Krishna Upanishad"],
  ["yajnavalkya-upanishad", "Yajnavalkya Upanishad"],
  ["varaha-upanishad", "Varaha Upanishad"],
  ["shatyayaniya-upanishad", "Shatyayaniya Upanishad"],
  ["hayagriva-upanishad", "Hayagriva Upanishad"],
  ["dattatreya-upanishad", "Dattatreya Upanishad"],
  ["garuda-upanishad", "Garuda Upanishad"],
  ["kalisantarana-upanishad", "Kalisantarana Upanishad"],
  ["jabali-upanishad", "Jabali Upanishad"],
  ["saubhagyalakshmi-upanishad", "Saubhagyalakshmi Upanishad"],
  ["sarasvatirahasya-upanishad", "Sarasvatirahasya Upanishad"],
  ["bahvricha-upanishad", "Bahvricha Upanishad"],
  ["muktika-upanishad", "Muktika Upanishad"],
 ] as const;
export const upanishadRegister = UPANISHAD_TARGETS.map(([work_id, title], index) => ({
  work_id, title, tradition: "Muktika 108", ordinal: index + 1,
  intended_publisher: "Gita Press", publisher_location: "Gorakhpur",
  edition_status: "not_selected", edition_id: null,
  catalogue_url: "https://gitapress.org/catalogue", catalogue_code: null,
  completeness: "unconfirmed", rights_status: "pending", review_status: "pending",
  indexed_passages: 0,
  citation_hierarchy: ["section", "mantra"],
  requested_assets: ["Sanskrit source text", "Hindi translation where licensed"],
  required_permissions: ["index", "quote", "remote_embedding", "audio"],
}));
